package hlaaftana.discordg

import groovy.transform.Memoized

enum Events {
	READY("READY"),
	MESSAGE_CREATE("MESSAGE_CREATE"),
	MESSAGE("MESSAGE_CREATE"),
	NEW_MESSAGE("MESSAGE_CREATE"),
	MESSAGE_DELETE("MESSAGE_DELETE"),
	MESSAGE_DELETED("MESSAGE_DELETE"),
	MESSAGE_UPDATE("MESSAGE_UPDATE"),
	MESSAGE_UPDATED("MESSAGE_UPDATE"),
	MESSAGE_ACK("MESSAGE_ACK"),
	CHANNEL("CHANNEL_CREATE"),
	NEW_CHANNEL("CHANNEL_CREATE"),
	CHANNEL_CREATE("CHANNEL_CREATE"),
	CHANNEL_UPDATE("CHANNEL_UPDATE"),
	CHANNEL_UPDATED("CHANNEL_UPDATE"),
	CHANNEL_DELETE("CHANNEL_DELETE"),
	CHANNEL_DELETED("CHANNEL_DELETE"),
	BAN("GUILD_BAN_ADD"),
	GUILD_BAN_ADD("GUILD_BAN_ADD"),
	UNBAN("GUILD_BAN_REMOVE"),
	GUILD_BAN_REMOVE("GUILD_BAN_REMOVE"),
	GUILD("GUILD_CREATE"),
	SERVER("GUILD_CREATE"),
	GUILD_CREATE("GUILD_CREATE"),
	SERVER_CREATE("GUILD_CREATE"),
	GUILD_CREATED("GUILD_CREATE"),
	SERVER_CREATED("GUILD_CREATE"),
	INITIAL_GUILD_CREATE("INITIAL_GUILD_CREATE"),
	GUILD_UPDATED("GUILD_UPDATE"),
	SERVER_UPDATED("GUILD_UPDATE"),
	GUILD_UPDATE("GUILD_UPDATE"),
	SERVER_UPDATE("GUILD_UPDATE"),
	SERVER_DELETE("GUILD_DELETE"),
	SERVER_DELETED("GUILD_DELETE"),
	GUILD_DELETE("GUILD_DELETE"),
	GUILD_DELETED("GUILD_DELETE"),
	GUILD_INTEGRATIONS_UPDATE("GUILD_INTEGRATIONS_UPDATE"),
	GUILD_EMOJIS_UPDATE("GUILD_EMOJIS_UPDATE"),
	MEMBER("GUILD_MEMBER_ADD"),
	MEMBER_JOINED("GUILD_MEMBER_ADD"),
	NEW_MEMBER("GUILD_MEMBER_ADD"),
	GUILD_MEMBER_ADD("GUILD_MEMBER_ADD"),
	MEMBER_UPDATE("GUILD_MEMBER_UPDATE"),
	MEMBER_UPDATED("GUILD_MEMBER_UPDATE"),
	GUILD_MEMBER_UPDATE("GUILD_MEMBER_UPDATE"),
	MEMBER_LEFT("GUILD_MEMBER_REMOVE"),
	MEMBER_KICKED("GUILD_MEMBER_REMOVE"),
	MEMBER_REMOVED("GUILD_MEMBER_REMOVE"),
	GUILD_MEMBER_REMOVE("GUILD_MEMBER_REMOVE"),
	ROLE("GUILD_ROLE_CREATE"),
	NEW_ROLE("GUILD_ROLE_CREATE"),
	GUILD_ROLE_CREATE("GUILD_ROLE_CREATE"),
	ROLE_UPDATE("GUILD_ROLE_UPDATE"),
	ROLE_UPDATED("GUILD_ROLE_UPDATE"),
	GUILD_ROLE_UPDATE("GUILD_ROLE_UPDATE"),
	GUILD_ROLE_DELETE("GUILD_ROLE_DELETE"),
	ROLE_DELETE("GUILD_ROLE_DELETE"),
	ROLE_DELETED("GUILD_ROLE_DELETE"),
	PRESENCE("PRESENCE_UPDATE"),
	PRESENCE_UPDATE("PRESENCE_UPDATE"),
	TYPING("TYPING_START"),
	TYPING_START("TYPING_START"),
	VOICE_STATE_UPDATE("VOICE_STATE_UPDATE"),
	VOICE_SERVER_UPDATE("VOICE_SERVER_UPDATE"),
	USER_UPDATE("USER_UPDATE"),
	USER_GUILD_SETTINGS_UPDATE("USER_GUILD_SETTINGS_UPDATE"),
	USER_SETTINGS_UPDATE("USER_SETTINGS_UPDATE"),
	GUILD_MEMBERS_CHUNK("GUILD_MEMBERS_CHUNK"),
	WEBSOCKET_CLOSE("CLOSE"),
	CLOSE("CLOSE"),
	UNRECOGNIZED("UNRECOGNIZED"),
	ALL("ALL")

	String type
	Events(String type){this.type = type}

	/**
	 * Returns an event name from a string by; <br>
	 * 1. Replacing "change" with "update" and "server" with "guild" (case insensitive), <br>
	 * 2. Making it uppercase, and <br>
	 * 3. Replacing spaces with underscores.
	 * @param str - the string.
	 * @return the event name.
	 */
	@Memoized
	static String parseEventType(String str){
		return str.toUpperCase().replaceAll(/\s+/, '_').replace("CHANGE", "UPDATE").replaceAll(/^(?!VOICE_)SERVER/, "GUILD")
	}

	@Memoized
	static Events get(type){ return (type instanceof Events) ? type : Events.class.enumConstants.find { it.type == this.parseEventType(type.toString()) } ?: Events.UNRECOGNIZED }
}
